project_id = "duclndrnymarwhmbtjgl"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.voice-assistant]
verify_jwt = false

[functions.whisper-transcribe]
verify_jwt = false

[functions.razorpay-payment]
verify_jwt = true

[functions.aadhaar-auth]
verify_jwt = false
